name: Publish on Github Packages
on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Set output
        id: vars
        run: echo "::set-output name=branch_name::${GITHUB_REF#refs/heads/}"
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Build Package
        run: mvn -s settings.xml clean compile -Dmaven.test.skip=true
      - name: Publish to GitHub Packages
        run: mvn -s settings.xml --batch-mode deploy
        env:
          # GITHUB_ACTOR: ${{ secrets.PUBLISHED_BY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
